export function Footer() {
  return (
    <footer className="border-t border-white/[0.06] py-8">
      <div className="mx-auto max-w-5xl px-6 flex flex-col items-center gap-2 text-sm text-zinc-500">
        <p>
          Generated by{" "}
          <span className="text-zinc-300 font-medium">YouTube AI Agent</span>{" "}
          — powered by Claude
        </p>
        <p className="text-xs text-zinc-600">
          Transcript extracted and summarized automatically from the video
        </p>
      </div>
    </footer>
  );
}
